version: '3'

services:
  mosquitto:
    image: eclipse-mosquitto:1.6.9
    container_name: mosquitto
    ports:
      - 1883:1883
    volumes:
      - ${PWD}/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ${DATA_DIR}/mosquitto/data:/mosquitto/data
      - ${DATA_DIR}/mosquitto/log:/mosquitto/log
    restart: always

  influxdb:
    image: influxdb:1.7.10
    container_name: influxdb
    environment:
      - INFLUXDB_DB=home_db
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    ports:
      - 8086:8086
    volumes:
      - ${DATA_DIR}/influxdb:/var/lib/influxdb
    restart: always

  chronograf:
    image: chronograf:latest
    ports:
      - '8888:8888'
    volumes:
      - ${DATA_DIR}/chronograf:/var/lib/chronograf
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_USERNAME=admin
      - INFLUXDB_PASSWORD=admin
  grafana:
    image: grafana/grafana:6.7.3
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - influxdb
    ports:
      - 3000:3000
    volumes:
      - ${DATA_DIR}/grafana:/var/lib/grafana:rw
    restart: always

  mqttbridge:
    build: ./bridge
    container_name: mqttbridge
    depends_on:
      - mosquitto
      - influxdb
    restart: always
